#!/bin/sh
PAGE=$1
ROOT=$2

sed "s,<head>,<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"https://www-old.gnome.org/default.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"https://foundation-old.gnome.org/foundation.css\" /><link rel=\"icon\" type=\"image/png\" href=\"https://www-old.gnome.org/img/logo/foot-16.png\" />,i;s,<body\([^>]*\)>,<body\1><div id=\"body\">,i;/<\/body>/,//d" $PAGE

cat <<-FOOT
</div>

<div id="hdr">
	<p class="none"></p>
	<div id="hdrNav">
		<a href="https://www.sfconservancy.org/">Conservancy's website</a> &middot;
		<a href="mailto:elections@sfconservancy.org">Email problems to: &lt;elections@sfconservancy.org&gt;</a> &middot;
		<a href="https://gitorious.org/conservancy/voting/">Source code for this site</a>

	</div>
</div>

</body>

</html>
FOOT
